name: Daily Update

on:
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨0点执行（UTC时间，需根据时区调整）
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies
        run: pip install requests

      - name: Run main script
        run: python main.py

      - name: Upload EPG files
        run: |
          wget -q https://epg.example.com/xmltv.xml -O output/epg.xml
          wget -q https://epg.example.com/fy.xml -O output/fy.xml

      - name: Commit changes
        run: |
          git config user.name "Bot"
          git config user.email "bot@example.com"
          git add output/
          git commit -m "Update: Channel list and EPG files" || true
          git push
