name: Daily Update

on:
  schedule:
    - cron: '55 0 */2 * *'  # 每2天凌晨00点55分执行任务（上海时区对应的UTC时间）
  workflow_dispatch:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: pip install requests

    - name: Run main script
      run: python main.py  # 生成output目录下的live.m3u和live.txt

    - name: Download EPG File
      run: |
        wget -q http://epg.51zmt.top:8000/e.xml -O output/epg.xml
        wget -q https://epg.v1.mk/fy.xml -O output/fy.xml
      # 下载多个EPG文件并统一存放至output目录（按需扩展）

    - name: Configure Git user
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Pull latest changes from remote (fast-forward only)
      run: git pull origin main --ff  # 强制快进拉取，确保本地与远程同步

    - name: Add changed files
      run: git add output/live.m3u output/live.txt output/*.xml

    - name: Commit and push if changes exist
      run: |
        if [ -n "$(git diff --staged --exit-code)" ]; then
          git commit -m "Update: Live streams and EPG files"
          git push origin main  # 移除不兼容的--ff-only，通过拉取确保快进状态
        else
          echo "No changes to commit"
        fi
    env:
      TZ: Asia/Shanghai  # 设置上海时区
      LANG: en_US.UTF-8
