name: Daily Update

on:
  schedule:
    - cron: '0 2 * * *'  # 每天凌晨2点执行（UTC时间，需根据时区调整）
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install aiohttp requests  # 添加异步依赖

      - name: Run processing script
        run: python main.py  # 执行主处理逻辑

      - name: Commit changes
        run: |
          git config user.name "Bot"
          git config user.email "bot@example.com"
          git add output/
          git commit -m "Update: $(date +'%Y-%m-%d %H:%M')" || true
          git push
